services:
  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql-nlw
    environment:
      - MYSQL_ROOT_PASSWORD=abroba
    ports:
      - '3336:3306'
    networks:
      - nlw-nertwork
networks:
  nlw-nertwork:
    driver: bridge
